FROM nvidia/cuda:11.3.1-devel-ubuntu20.04

RUN apt-get update && apt-get install wget git -yq
RUN apt-get install build-essential g++ gcc -y
ENV DEBIAN_FRONTEND noninteractive
# Unsure if openmpi is needed
# RUN apt-get update && apt-get install libgl1-mesa-glx libglib2.0-0 libxcb-* \
# openmpi-bin openmpi-common libopenmpi-dev libgtk2.0-dev -y  

# Install miniconda
ENV CONDA_DIR /opt/conda

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:/usr/local/bin:$PATH
# general packages
RUN conda install python=3.8
RUN conda install numpy=1.23
RUN conda install -c anaconda jupyter
RUN echo "numpy==1.23.*" > /opt/conda/conda-meta/pinned
RUN conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
RUN conda install conda=22.11 
RUN conda install -c conda-forge setuptools=59.5

# Make sure CUDA is visible
# ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:$LD_LIBRARY_PATH
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
# ARG TORCH_CUDA_ARCH_LIST="8.9"
# Install pointgroup_ops
RUN apt-get install libsparsehash-dev
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
COPY lib /lib
RUN cd /lib/pointgroup_ops && python setup.py develop

# Install spconv
RUN conda install libboost && pip install pccm
RUN pip install spconv-cu113

# Install pointnet2
# RUN cd /lib/pointnet2 && python setup.py install

# Install faiss
RUN conda install -c conda-forge faiss-gpu

